name: Map Generator

on:
  push:
    branches:
      - main
      - issue#5
    paths:
      - 'fits_import/fits2csv.py'
      - 'map/map_example.py'
      - 'map/map_generator_action.py' 

permissions:
  contents: write

jobs:
  deploy-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute map
        run: python map/map_generator_action.py

      - name: Prepare deployment
        run: |
          mkdir public
          mkdir public/map
          cp README.md public/README.md
          mv map/index.html public/map/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          jekyll: true