name: Preparing GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install astropy numpy loguru pandas plotly sphinx shibuya
      
      - name: Creating Directories
        run: |
          mkdir public
          mkdir public/map
          mkdir public/docs


      - name: Creating Documentation
        run: |
          sphinx-apidoc -o docs/source/api/dnn ./dnn/
          sphinx-apidoc -o docs/source/api/fits_import ./fits_import/
          sphinx-apidoc -o docs/source/api/imports ./imports/
          sphinx-apidoc -o docs/source/api/map ./map/
          rm -rf docs/build
          cd docs
          make dirhtml
          cd ..

      - name: Execute Map Generator
        run: python map/map_generator_action.py

      - name: Moving files
        run: |

          mv docs/build/dirhtml/* public/docs/
          cp README.md public/README.md
          mv map/index.html public/map/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true