name: Map Generator

on:
  push:
    branches:
      - main
      - issue#5
    paths:
      - 'fits_import/fits2csv.py'
      - 'map/map_example.py'
      - 'map/map_generator_action.py' 

permissions:
  contents: write

jobs:
  deploy-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute map
        run: python map/map_generator_action.py

      # Creiamo una cartella pulita dove mettere SOLO ci√≤ che va online
      - name: Prepare deployment
        run: |
          mkdir public
          mkdir public/map
          # Sposto il file generato da 'map/' alla cartella di pubblicazione
          cp README.md public/README.md
          mv map/index.html public/map/index.html

      # Carichiamo il contenuto di 'public' sul branch 'gh-pages'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true # Mantiene il branch gh-pages pulito e leggero (1 solo commit)